services:
  api:
    build: .
    ports:
      - "${PORT:-8555}:8555"
    environment:
      - FASTWRAP_API_KEY=${FASTWRAP_API_KEY}
      - PORT=${PORT}
      - HOST=${HOST}
      - MODEL=${MODEL}
      - MODEL_KEY=${MODEL_KEY}
      - REDIS_HOST=${REDIS_HOST} # FOR DEVELOPMENT
      # - REDIS_HOST=redis # FOR PROD RELEASE
      - REDIS_PORT=${REDIS_PORT}
      # - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST} # FOR DEVELOPMENT
      # - REDIS_HOST=redis # FOR PROD RELEASE
      - REDIS_PORT=${REDIS_PORT}
      # - REDIS_PORT=6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
